version: "3.3"

services:
  mattermost:
    image: mattermost/mattermost-preview:latest
    restart: always
    extra_hosts:
      - dockerhost:127.0.0.1
    ports:
      - 8065:8065

  focalboard:
    image: mattermost/focalboard
    ports:
      - 8000:8000
    restart: always 