version: '3.7'

services:
  telegram-bot-api:
    image: telegrambot/telegram-bot-api:latest
    container_name: telegram-bot-api
    environment:
      - DB_TYPE=sqlite
      - DB_PATH=/data/database.db
      - LISTEN_PORT=5000
      - TELEGRAM_API_ID=your-telegram-api-id
      - TELEGRAM_API_HASH=your-telegram-api-hash
      - TELEGRAM_BOT_TOKEN=your-bot-token
    volumes:
      - telegram_bot_api_data:/data
    ports:
      - 5000:5000
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegram_bot_api.rule=Host(`telegram_bot_api.elmakchi.ir`)"
      - "traefik.http.routers.telegram_bot_api.entrypoints=websecure"
      - "traefik.http.routers.telegram_bot_api.tls.certresolver=myresolver"
      - "traefik.http.services.telegram_bot_api.loadbalancer.server.port=80"
    networks:
      - traefik_reverse_proxy

volumes:
  telegram_bot_api_data:

networks:
  traefik_reverse_proxy:
    external: true