version: '3.9'

services:
  drawdb:
    image: xinsodev/drawdb
    container_name: drawdb
    ports:
      - 3500:80
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawdb.rule=Host(`drawdb.elmakchi.ir`)"
      - "traefik.http.routers.drawdb.entrypoints=websecure"
      - "traefik.http.routers.drawdb.tls.certresolver=myresolver"
      - "traefik.http.services.drawdb.loadbalancer.server.port=80"
    networks:
      - traefik_reverse_proxy

networks:
  traefik_reverse_proxy:
    external: true
