version: "3"

networks:
  gitea:
    external: false

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=gitea_user
      - POSTGRES_PASSWORD=gitea_pass
      - POSTGRES_DB=gitea_db
    volumes:
      - ./gitea-data:/var/lib/postgresql/data

  gitea:
    image: gitea/gitea:latest
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres
      - GITEA__database__NAME=gitea_db
      - GITEA__database__USER=gitea_user
      - GITEA__database__PASSWD=gitea_pass
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - postgres

volumes:
  gitea:
  gitea-data: