version: "3.8"

services:
  joomla:
    image: joomla:latest
    restart: always
    ports:
      - 8080:80
    environment:
      JOOMLA_DB_HOST: db
      JOOMLA_DB_USER: mysql_user_joomla
      JOOMLA_DB_PASSWORD: mysql_pass_joomla
      JOOMLA_DB_NAME: mysql_joomla
      JOOMLA_SITE_NAME: Site Name
      JOOMLA_ADMIN_USER: Samad Elmakchi
      JOOMLA_ADMIN_USERNAME: admin
      JOOMLA_ADMIN_PASSWORD: 61656165
      JOOMLA_ADMIN_EMAIL: samad.elmakchi@gmail.com
    volumes:
      - ./joomla_data:/var/www/html
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joomla.rule=Host(`joomla.elmakchi.ir`)"
      - "traefik.http.routers.joomla.entrypoints=websecure"
      - "traefik.http.routers.joomla.tls.certresolver=myresolver"
      - "traefik.http.services.joomla.loadbalancer.server.port=80"
 
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass_joomla
      MYSQL_DATABASE: mysql_joomla
      MYSQL_USER: mysql_user_joomla
      MYSQL_PASSWORD: mysql_pass_joomla
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - traefik_reverse_proxy

volumes:
  joomla_data:
  db_data:

networks:
  traefik_reverse_proxy:
    external: true
