version: "3.3"
services:
  poste.io:
    image: analogic/poste.io
    network_mode: host
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./data:/data
    
    hostname: mail.example.com
    tty: true
    restart: always