services:
  macos:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "15"
      DISK_SIZE: "256G"
      RAM_SIZE: "6G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    volumes:
      - ./storage:/storage
    ports:
      - 8007:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    stop_grace_period: 2m