version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    restart: always
    hostname: rabbitmq.elmakchi.ir
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15672:15672
    volumes:
      - './rabbitmq_data:/data'
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.elmakchi.ir`)"
      - "traefik.http.routers.rabbitmq.entrypoints=websecure"
      - "traefik.http.routers.rabbitmq.tls.certresolver=myresolver"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=8080"

volumes:
  rabbitmq_data:

networks:
  traefik_reverse_proxy:
    external: true

