version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
      
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000

