version: '2.1'
services:
  trudesk:
    image: polonel/trudesk:latest
    restart: always
    ports:
      - 8118:8118
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    environment:
      NODE_ENV: production
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      USE_XFORWARDIP: "true"
    volumes:
      - ./trudesk_uploads:/usr/src/trudesk/public/uploads
      - ./trudesk_backups:/usr/src/trudesk/backups
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trudesk.rule=Host(`trudesk.elmakchi.ir`)"
      - "traefik.http.routers.trudesk.entrypoints=websecure"
      - "traefik.http.routers.trudesk.tls.certresolver=myresolver"
      - "traefik.http.services.trudesk.loadbalancer.server.port=8118"

  mongo:
    image: mongo:5.0-focal
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/var/lib/mongo
      - ./mongo_data:/data/db:rw
    networks:
      - traefik_reverse_proxy

volumes:
  trudesk_uploads:
  trudesk_backups:
  mongo:
  mongo_data:

networks:
  traefik_reverse_proxy:
    external: true
