version: '3'

services:
  nginx-cdn:
    container_name: nginx_cdn
    image: nginx:latest
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cdn.rule=Host(`cdn.elmakchi.ir`)"
      - "traefik.http.routers.cdn.entrypoints=websecure"
      - "traefik.http.routers.cdn.tls.certresolver=myresolver"
      - "traefik.http.services.cdn.loadbalancer.server.port=80"
    volumes:
      - ./html:/usr/share/nginx/html 
    restart: always
   
networks:
  traefik_reverse_proxy:
    external: true

volumes:
  html: