version: '3.8'

services:
  fastgpt:
    image: fastgpt/fastgpt:latest
    container_name: fastgpt
    restart: always
    ports:
      - "5000:5000"                            # پورت پیش‌فرض برای دسترسی به API
    environment:
      - FASTGPT_API_KEY=your_api_key_here      # کلید API شما (در صورت نیاز به اتصال به منابع خارجی)
      - FASTGPT_MODEL=GPT-4                    # مدل مورد استفاده (مثلاً GPT-3 یا GPT-4)
      - FASTGPT_HOST=0.0.0.0                   # تنظیمات میزبانی
      - FASTGPT_PORT=5000                      # پورت برای دسترسی به API
    volumes:
      - fastgpt_data:/app/data                 # مسیر داده‌ها و تنظیمات
    networks:
      - fastgpt_network
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastgpt.rule=Host(`fastgpt.elmakchi.ir`)"
      - "traefik.http.routers.fastgpt.entrypoints=websecure"
      - "traefik.http.routers.fastgpt.tls.certresolver=myresolver"
      - "traefik.http.services.fastgpt.loadbalancer.server.port=5000"

  redis:
    image: redis:latest
    container_name: fastgpt_redis
    restart: always
    ports:
      - "6379:6379"  # پورت برای ارتباط با Redis
    networks:
      - fastgpt_network
      - traefik_reverse_proxy

networks:
  fastgpt_network:
    driver: bridge
  traefik_reverse_proxy:
    external: true

volumes:
  fastgpt_data:
  

