version: "3.8"

services:
  wordpress:
    container_name: wordpress
    depends_on:
      - mysql
    image: wordpress:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: mysql_wordpress_db
      WORDPRESS_DB_USER: mysql_wordpress_user
      WORDPRESS_DB_PASSWORD: mysql_wordpress_pass
      PHP_INI_UPLOAD_MAX_FILESIZE: 256M
    networks:
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.elmakchi.ir`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=myresolver"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"

  mysql:
    container_name: mysql_wordpress
    image: mysql:latest
    volumes:
      - ./wordpress-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mysql_wordpress_db
      MYSQL_USER: mysql_wordpress_user
      MYSQL_PASSWORD: mysql_wordpress_pass
    restart: always
    networks:
      - traefik_reverse_proxy

volumes:
  wordpress:
  wordpress-db:

networks:
  traefik_reverse_proxy:
    external: true