version: "3.8"

services:
  semaphore:
    image: semaphoreui/semaphore:latest
    ports:
      - 3000:3000
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin
      SEMAPHORE_ADMIN_NAME: Administrator
      SEMAPHORE_ADMIN_EMAIL: admin#example.com


# Ansible - Terraform - OpenTofu - Bash - PowerShell - Pulumi - Docker