version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: zabbix-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zabbix-net
      - traefik_reverse_proxy

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
    depends_on:
      - mysql
    ports:
      - "10051:10051"
    networks:
      - zabbix-net
      - traefik_reverse_proxy

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    restart: unless-stopped
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: "UTC"
    depends_on:
      - mysql
      - zabbix-server
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - zabbix-net
      - traefik_reverse_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zabbix.rule=Host(`zabbix.elmakchi.ir`)"
      - "traefik.http.routers.zabbix.entrypoints=websecure"
      - "traefik.http.routers.zabbix.tls.certresolver=myresolver"
      - "traefik.http.services.zabbix.loadbalancer.server.port=8080"

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: unless-stopped
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_ACTIVE_SERVER: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net
      - traefik_reverse_proxy

volumes:
  mysql_data:

networks:
  zabbix-net:
    driver: bridge
  traefik_reverse_proxy:
    external: true
