version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: always
    ports:
      - "8888:8888"
    depends_on:
      - influxdb

volumes:
  influxdb_data: