version: '3'
services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./rancher_data:/var/lib/rancher
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rancher.rule=Host(`rancher.elmakchi.ir`)"
      - "traefik.http.routers.rancher.entrypoints=websecure"
      - "traefik.http.routers.rancher.tls.certresolver=myresolver"
      - "traefik.http.services.rancher.loadbalancer.server.port=443"
    networks:
      - traefik_reverse_proxy

volumes:
  rancher_data:

networks:
  traefik_reverse_proxy:
    external: true